version: '3.1'
services:
  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /var/www/site
    volumes:
      - '.:/var/www/site'
      - './data/txt/index.txt:/etc/txt/index.txt'
  webserver:
    image: 'nginx:alpine'
    working_dir: /var/www/site
    volumes:
      - '.:/var/www/site'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8081:81'
    links:
      - mysql
  mysql:
    image: 'mysql:8.0'
    working_dir: /var/www/site
    volumes:
      - '.:/var/www/site'
      - './data/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '9081:3306'